use_frameworks!

platform :ios, '8.0'

target 'CPTGridListManager_Example' do
  pod 'CPTGridListManager', :path => '../'

  target 'CPTGridListManager_Tests' do
    inherit! :search_paths

    
  end
end
